### ISSUE TITLE
Peptide Coverage Residue Plot

### ISSUE THREAD

**Issue by nlgittens** [ococrook/RexMS#2]
## Is the feature request related to a problem?

More of a cosmetic issue: changing residue fraction to residue number for legibility. CoverageHeatMap function is defining nrow as max(res$End), so I'm not sure why this doesn't work.
![image](https://github.com/ococrook/RexMS/assets/90684994/36e933a6-4aa8-4825-8d5f-a17d9947a177)

## Describe the solution

Multiply xlabels by max(res$End)

**Comment by ococrook** [comment]
Not an obious solution to make this prettier. Might have to switch to heatmap or pheatmap or ggplot and play around with the aesthetics a bit.

**Comment by nlgittens** [comment]
I wouldn't worry about it in this case then. We and most people will also have tools for sequence coverage plots, and so what is in the package still works as sanity check to examine coverage post-cleaning. I'll close the issue.
